services:
  mysql:
    image: mysql:8.0
    container_name: mysql_laravel
    restart: always
    environment:
      MYSQL_DATABASE: apiLavarel
      MYSQL_USER: William
      MYSQL_PASSWORD: Will3443*
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_laravel
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    deploy:
      resources:
        limits:
          memory: 150M
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
